repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.71.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
      args:
          - --args=--html=false --anchor=false
# tflint requires additional installation and AWS permissions, so is currently optional
#    - id: terraform_tflint
#      args:
#        - '--args=--config=__GIT_WORKING_DIR__/.tflint.hcl'
